# The name of the virtual environment to be created to install package dependencies
#
name: WebAppChallenge

# Conda channels are the locations where packages are stored. They serve as the base downloading packages
# More info: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/channels.html
channels:
  - defaults
  - conda-forge

# The (needed) packages to be installed, via the MAIN Conda package manger.
#
# It is STRONGLY recommended to install packages via Conda. ONLY WHEN IT IS NOT AVAILABLE via Conda channels (i.e. default / conda-forge),
# THEN AND ONLY THEN, utilize pip package manager to register and download the concerning package.
# Thus: Conda is the MAIN package manager, Pip is the SECONDARY aka FALLBACK package manager.

# Adding dependencies must also include a short line describing what the package is and a link to the documentation of the concerning package,
# thus the format is:
#
#   - package-name=version     # Short description of what the package entails - https://link-to-documentation-of-the-concerning-package
#
# Please adhere to the format, as it will make having a proper overview of dependencies and a quick reference to documentation of a dependency insightful,
# for yourself, for others team members, other teams, now and in the future.

# Add dependencies that comes with this project to the 'dependencies' block
dependencies:
# - package-name=version              # Short description of what the package entails - https://link-to-documentation-of-the-concerning-package

  # The (needed) packages to be installed, via the SECONDARY aka FALLBACK Pip package manger, because is NOT AVAILABLE via Conda,
  # but IS AVAILABLE via pip packages, then and only then, register the concerning package in the `pip` dependencies block.
  - pip:

      - Flask==1.1.2
      - numpy==1.18.5
      - pandas==1.0.4
      - pylint==2.5.3
      - python-dateutil==2.8.1
      #WINDOWS_PACKAGE#     # Type of tree model (Needed for WINDOWS) - yes, this is added as duplicate and marked with the #WINDOWS_PACKAGE# placeholder, otherwise it will not work on WINDOWS - https://xgboost.readthedocs.io/en/latest/

